spring.application.name=Mesa_do_Campo_Back
spring.datasource.url=${BANCO_URL}
spring.datasource.username=${BANCO_USERNAME}
spring.datasource.password=${BANCO_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.show-sql=true
server.port=${SERVER_PORT:8080}
server.forward-headers-strategy=framework
springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
chave.privada=${CHAVE_PRIVADA}
chave.publica=${CHAVE_PUBLICA:}
