spring.application.name=Mesa_do_Campo_Back
spring.datasource.url=${BANCO_URL}
spring.datasource.username=${BANCO_USERNAME}
spring.datasource.password=${BANCO_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.show-sql=true
server.port=8081